version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"

  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
  grafana_data:
